name: Push production to server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Read node version from .nvmrc
        id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'jkl3458jks0w390jkd'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - run: rsync -avz --delete ./public/ .htaccess ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.TARGET }}
